version: '3'
services:
  bitcoind:
    image: lightninglabs/bitcoin-core:26
    container_name: bitcoind
    restart: unless-stopped
    ports:
      - "18443:18443"
      - "18444:18444"
      - "28332:28332"
      - "28333:28333"
    networks:
      regtest:
        aliases:
          - bitcoind
    command:
      - "-txindex"
      - "-regtest"
      - "-rest"
      - "-printtoconsole"
      - "-zmqpubrawblock=tcp://0.0.0.0:28332"
      - "-zmqpubrawtx=tcp://0.0.0.0:28333"
      - "-rpcport=18443"
      - "-rpcbind=0.0.0.0"
      - "-rpcauth=lightning:8492220e715bbfdf5f165102bfd7ed4$$88090545821ed5e9db614588c0afbad575ccc14681fb77f3cae6899bc419af67"
      - "-rpcallowip=0.0.0.0/0"
      - "-fallbackfee=0.0002"
      - "-peerblockfilters=1"
      - "-blockfilterindex=1"
      - "-wallet=/home/bitcoin/.bitcoin/regtest/wallets/miner"
    environment:
      - HOME=/home/bitcoin
    volumes:
      - bitcoind:/home/bitcoin/.bitcoin


  electrs:
    image: mempool/electrs
    container_name: electrs
    restart: unless-stopped
    ports:
      - "3004:3000"
    networks:
      - regtest
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - bitcoind:/home/user/.bitcoin
    user: "0:0"
    depends_on:
      - bitcoind
    command:
      - "-vvv"
      - "--timestamp"
      - "--network=regtest"
      - "--cookie=lightning:lightning"
      - "--daemon-rpc-addr=bitcoind:18443"
      - "--http-addr=0.0.0.0:3000"
      - "--cors=http://localhost:3002"
      - "--daemon-dir=/home/user/.bitcoin"
      - "--db-dir=/home/user/.bitcoin/db"


  esplora:
    image: guggero/esplora
    container_name: esplora
    restart: unless-stopped
    ports:
      - "3002:5000"
    networks:
      - regtest
    environment:
      - API_URL=http://localhost:3004/
      - NODE_ENV=production
    command:
      - "npm"
      - "run"
      - "dev-server"


  alice:
    image: lightninglabs/lightning-terminal:v0.14.1-alpha
    container_name: alice 
    restart: unless-stopped
    ports:
      - "10011:10009"
      - "9741:9735"
      - "8091:8080"
      - "8443:8443"
    networks:
      regtest:
        aliases:
          - alice
    volumes:
      - "alice:/root"
    depends_on:
      - bitcoind
    command:
      - "--httpslisten=[::]:8443"
      - "--uipassword=justregtestnothingtosteal"
      - "--network=regtest"
      - "--lnd-mode=integrated"
      - "--lnd.alias=alice"
      - "--lnd.rpclisten=0.0.0.0:10009"
      - "--lnd.restlisten=0.0.0.0:8080"
      - "--lnd.color=#cccccc"
      - "--lnd.noseedbackup"
      - "--lnd.bitcoin.active"
      - "--lnd.bitcoin.regtest"
      - "--lnd.bitcoin.node=bitcoind"
      - "--lnd.bitcoind.rpchost=bitcoind"
      - "--lnd.bitcoind.rpcuser=lightning"
      - "--lnd.bitcoind.rpcpass=lightning"
      - "--lnd.bitcoind.zmqpubrawblock=tcp://bitcoind:28332"
      - "--lnd.bitcoind.zmqpubrawtx=tcp://bitcoind:28333"
      - "--lnd.externalip=alice"
      - "--lnd.tlsextradomain=alice"
      - "--lnd.accept-keysend"
      - "--lnd.debuglevel=trace,SRVR=debug,PEER=info,BTCN=warn"
      - "--lnd.rpcmiddleware.enable"
      - "--lnd.protocol.wumbo-channels"
      - "--lnd.protocol.option-scid-alias"
      - "--lnd.protocol.zero-conf"
      - "--lnd.protocol.simple-taproot-chans"
      - "--lnd.protocol.simple-taproot-overlay-chans"
      - "--lnd.accept-keysend"
      - "--loop.server.host=loopserver:11009"
      - "--loop.server.notls"
      - "--pool.auctionserver=localhost:12009"
      - "--pool.tlspathauctserver=/home/guggero/.auctionserver/tls.cert"
      - "--pool.fakeauth"
      - "--autopilot.disable"
      - "--taproot-assets.proofcourieraddr=universerpc://localhost:8443"
      - "--taproot-assets.universe.public-access=rw"
      - "--taproot-assets.universe.sync-all-assets"
      - "--taproot-assets.universerpccourier.initialbackoff=2s"
      - "--taproot-assets.universerpccourier.maxbackoff=30s"
      - "--taproot-assets.allow-public-uni-proof-courier"
      - "--taproot-assets.allow-public-stats"
      - "--taproot-assets.experimental.rfq.priceoracleaddress=use_mock_price_oracle_service_promise_to_not_use_on_mainnet"
      - "--taproot-assets.experimental.rfq.mockoracleassetsperbtc=6500000"


  bob:
    image: lightninglabs/lightning-terminal:v0.14.1-alpha
    container_name: bob 
    restart: unless-stopped
    ports:
      - "10012:10009"
      - "9742:9735"
      - "8092:8080"
      - "8444:8443"
    networks:
      regtest:
        aliases:
          - bob
    volumes:
      - "bob:/root"
    depends_on:
      - bitcoind
    command:
      - "--httpslisten=[::]:8443"
      - "--uipassword=justregtestnothingtosteal"
      - "--network=regtest"
      - "--lnd-mode=integrated"
      - "--lnd.alias=bob"
      - "--lnd.rpclisten=0.0.0.0:10009"
      - "--lnd.restlisten=0.0.0.0:8080"
      - "--lnd.color=#cccccc"
      - "--lnd.noseedbackup"
      - "--lnd.bitcoin.active"
      - "--lnd.bitcoin.regtest"
      - "--lnd.bitcoin.node=bitcoind"
      - "--lnd.bitcoind.rpchost=bitcoind"
      - "--lnd.bitcoind.rpcuser=lightning"
      - "--lnd.bitcoind.rpcpass=lightning"
      - "--lnd.bitcoind.zmqpubrawblock=tcp://bitcoind:28332"
      - "--lnd.bitcoind.zmqpubrawtx=tcp://bitcoind:28333"
      - "--lnd.externalip=bob"
      - "--lnd.tlsextradomain=bob"
      - "--lnd.accept-keysend"
      - "--lnd.debuglevel=trace,SRVR=debug,PEER=info,BTCN=warn"
      - "--lnd.rpcmiddleware.enable"
      - "--lnd.protocol.wumbo-channels"
      - "--lnd.protocol.option-scid-alias"
      - "--lnd.protocol.zero-conf"
      - "--lnd.protocol.simple-taproot-chans"
      - "--lnd.protocol.simple-taproot-overlay-chans"
      - "--lnd.accept-keysend"
      - "--loop.server.host=loopserver:11009"
      - "--loop.server.notls"
      - "--pool.auctionserver=localhost:12009"
      - "--pool.tlspathauctserver=/home/guggero/.auctionserver/tls.cert"
      - "--pool.fakeauth"
      - "--autopilot.disable"
      - "--taproot-assets.proofcourieraddr=universerpc://localhost:8443"
      - "--taproot-assets.universe.public-access=rw"
      - "--taproot-assets.universe.sync-all-assets"
      - "--taproot-assets.universerpccourier.initialbackoff=2s"
      - "--taproot-assets.universerpccourier.maxbackoff=30s"
      - "--taproot-assets.allow-public-uni-proof-courier"
      - "--taproot-assets.allow-public-stats"
      - "--taproot-assets.experimental.rfq.priceoracleaddress=use_mock_price_oracle_service_promise_to_not_use_on_mainnet"
      - "--taproot-assets.experimental.rfq.mockoracleassetsperbtc=6500000"
      - "--taproot-assets.universe.federationserver=alice:8443"


  charlie:
    image: lightninglabs/lnd:v0.18.5-beta
    container_name: charlie 
    restart: unless-stopped
    ports:
      - "10013:10009"
      - "9743:9735"
      - "8093:8080"
    networks:
      regtest:
        aliases:
          - charlie
    volumes:
      - "charlie:/root/.lnd"
    depends_on:
      - bitcoind
    command:
      - "--logdir=/root/.lnd"
      - "--alias=charlie"
      - "--rpclisten=0.0.0.0:10009"
      - "--restlisten=0.0.0.0:8080"
      - "--color=#cccccc"
      - "--noseedbackup"
      - "--bitcoin.active"
      - "--bitcoin.regtest"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpchost=bitcoind"
      - "--bitcoind.rpcuser=lightning"
      - "--bitcoind.rpcpass=lightning"
      - "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332"
      - "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333"
      - "--debuglevel=debug"
      - "--externalip=charlie"
      - "--tlsextradomain=charlie"
      - "--accept-keysend"
      - "--protocol.wumbo-channels"


  dave:
    image: lightninglabs/lnd:v0.18.5-beta
    container_name: dave 
    restart: unless-stopped
    ports:
      - "10014:10009"
      - "9744:9735"
      - "8094:8080"
    networks:
      regtest:
        aliases:
          - dave
    volumes:
      - "dave:/root/.lnd"
    depends_on:
      - bitcoind
    command:
      - "--logdir=/root/.lnd"
      - "--alias=dave"
      - "--rpclisten=0.0.0.0:10009"
      - "--restlisten=0.0.0.0:8080"
      - "--color=#cccccc"
      - "--noseedbackup"
      - "--bitcoin.active"
      - "--bitcoin.regtest"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpchost=bitcoind"
      - "--bitcoind.rpcuser=lightning"
      - "--bitcoind.rpcpass=lightning"
      - "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332"
      - "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333"
      - "--debuglevel=debug"
      - "--externalip=dave"
      - "--tlsextradomain=dave"
      - "--accept-keysend"
      - "--protocol.wumbo-channels"


  erin:
    image: lightninglabs/lnd:v0.18.5-beta
    container_name: erin
    restart: unless-stopped
    ports:
      - "10015:10009"
      - "9745:9735"
      - "8095:8080"
    networks:
      regtest:
        aliases:
          - erin
    volumes:
      - "erin:/root/.lnd"
    depends_on:
      - bitcoind
    command:
      - "--logdir=/root/.lnd"
      - "--alias=erin"
      - "--rpclisten=0.0.0.0:10009"
      - "--restlisten=0.0.0.0:8080"
      - "--color=#cccccc"
      - "--noseedbackup"
      - "--bitcoin.active"
      - "--bitcoin.regtest"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpchost=bitcoind"
      - "--bitcoind.rpcuser=lightning"
      - "--bitcoind.rpcpass=lightning"
      - "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332"
      - "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333"
      - "--debuglevel=debug"
      - "--externalip=erin"
      - "--tlsextradomain=erin"
      - "--listen=0.0.0.0:9735"
      - "--accept-keysend"
      - "--protocol.wumbo-channels"
      - "--protocol.option-scid-alias"
      - "--protocol.zero-conf"
      - "--maxchansize=2100000000000000"


  fabia:
    image: lightninglabs/lnd:v0.18.5-beta
    container_name: fabia
    restart: unless-stopped
    ports:
      - "10016:10009"
      - "9746:9735"
      - "8096:8080"
    networks:
      regtest:
        aliases:
          - fabia
    volumes:
      - "fabia:/root/.lnd"
    depends_on:
      - bitcoind
    command:
      - "--logdir=/root/.lnd"
      - "--alias=fabia"
      - "--rpclisten=0.0.0.0:10009"
      - "--restlisten=0.0.0.0:8080"
      - "--color=#cccccc"
      - "--noseedbackup"
      - "--bitcoin.active"
      - "--bitcoin.regtest"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpchost=bitcoind"
      - "--bitcoind.rpcuser=lightning"
      - "--bitcoind.rpcpass=lightning"
      - "--bitcoind.zmqpubrawblock=tcp://bitcoind:28332"
      - "--bitcoind.zmqpubrawtx=tcp://bitcoind:28333"
      - "--debuglevel=debug"
      - "--externalip=fabia"
      - "--tlsextradomain=fabia"
      - "--listen=0.0.0.0:9735"
      - "--accept-keysend"
      - "--protocol.wumbo-channels"
      - "--protocol.option-scid-alias"
      - "--protocol.zero-conf"
      - "--maxchansize=2100000000000000"

  nifty:
    image: elementsproject/lightningd:v24.11.1
    container_name: nifty
    restart: unless-stopped
    ports:
      - "9747:9735"
    networks:
      - regtest
    volumes:
      - "nifty:/root/.lightning"
    depends_on:
      - bitcoind
    command:
      - "--bitcoin-rpcconnect=bitcoind"
      - "--bitcoin-rpcuser=lightning"
      - "--bitcoin-rpcpassword=lightning"
      - "--network=regtest"
      - "--plugin-dir=/usr/libexec/c-lightning/plugins"
      - "--alias=nifty"
      - "--log-level=debug"
      - "--bind-addr=0.0.0.0:9735"

  rusty:
    image: elementsproject/lightningd:v24.11.1
    container_name: rusty
    restart: unless-stopped
    ports:
      - "9748:9735"
    networks:
      - regtest
    volumes:
      - "rusty:/root/.lightning"
    depends_on:
      - bitcoind
    command:
      - "--bitcoin-rpcconnect=bitcoind"
      - "--bitcoin-rpcuser=lightning"
      - "--bitcoin-rpcpassword=lightning"
      - "--network=regtest"
      - "--plugin-dir=/usr/libexec/c-lightning/plugins"
      - "--alias=rusty"
      - "--log-level=debug"
      - "--bind-addr=0.0.0.0:9735"

  snyke:
    image: elementsproject/lightningd:v24.11.1
    container_name: snyke
    restart: unless-stopped
    ports:
      - "9749:9735"
    networks:
      - regtest
    volumes:
      - "snyke:/root/.lightning"
    depends_on:
      - bitcoind
    command:
      - "--bitcoin-rpcconnect=bitcoind"
      - "--bitcoin-rpcuser=lightning"
      - "--bitcoin-rpcpassword=lightning"
      - "--network=regtest"
      - "--plugin-dir=/usr/libexec/c-lightning/plugins"
      - "--alias=snyke"
      - "--log-level=debug"
      - "--bind-addr=0.0.0.0:9735"

  loopserver:
    image: lightninglabs/loopserver:latest
    container_name: loopserver
    restart: unless-stopped
    ports:
      - "11009:11009"
    networks:
      - regtest
    volumes:
      - ./data/fabia:/tmp
    depends_on:
      - fabia
    command:
      - "daemon"
      - "--maxamt=5000000"
      - "--bitcoin.host=bitcoind:18443"
      - "--bitcoin.user=lightning"
      - "--bitcoin.password=lightning"
      - "--bitcoin.zmqpubrawblock=tcp://bitcoind:28332"
      - "--bitcoin.zmqpubrawtx=tcp://bitcoind:28333"
      - "--lnd.host=fabia:10009"
      - "--lnd.macaroondir=/tmp"
      - "--lnd.tlspath=/tmp/tls.cert"

networks:
  regtest:

volumes:
  bitcoind:
  alice:
  bob:
  charlie:
  dave:
  erin:
  fabia:
  nifty:
  rusty:
  snyke:
